# Build Geth in a stock Go builder container
FROM golang:1.11-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers

ADD . /go/src/github.com/Onther-Tech/plasma-evm
RUN cd /go/src/github.com/Onther-Tech/plasma-evm && \
    build/env.sh go run build/ci.go install cmd/bootnode/main.go

# Bootnode image
FROM alpine:latest 

COPY docker.bootnode.sh boot.key /usr/local/bin/
COPY --from=builder /go/src/github.com/Onther-Tech/plasma-evm/build/bin/main /usr/local/bin/bootnode
WORKDIR /usr/local/bin
