version: '3'
services:
  bootnode:
    image: plasma-evm/bootnode
    build:
      context: .
      dockerfile: Dockerfile.bootnode
    networks:
      default:
        ipv4_address: ${SUBNET}.${BOOTNODE_IP}
    command: sh docker.bootnode.sh

  child_operator:
    image: plasma-evm/child
    volumes:
      - '${LOGDIR}_Operator:/usr/local/bin/log'
    build:
      context: .
      dockerfile: Dockerfile.plasma
    networks:
      default:
        ipv4_address: ${SUBNET}.${OPERATOR_IP}
    healthcheck:
      test: ["CMD-SHELL", "sh health_checker.sh || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
    environment:
      - ROOTCHAIN_ADDR=${SUBNET}.${ROOTCHAIN_IP}
      - BOOTNODE_ADDR=${SUBNET}.${BOOTNODE_IP}
    command: sh docker.operator.pls.sh

  child_user:
    image: plasma-evm/child
    build:
        context: .
        dockerfile: Dockerfile.plasma
    volumes:
      - '${LOGDIR}_User:/usr/local/bin/log' 
    networks:
      default:
        ipv4_address: ${SUBNET}.${USER_IP}
    environment:
      - ROOTCHAIN_ADDR=${SUBNET}.${ROOTCHAIN_IP}
      - OPERATOR_ADDR=${SUBNET}.${OPERATOR_IP}
      - BOOTNODE_ADDR=${SUBNET}.${BOOTNODE_IP}
    ports:
      - "0.0.0.0:48547:8547"
      - "0.0.0.0:48548:8548"
    command: sh docker.user.pls.sh

networks:
  default:
    external:
      name: plasma_tokamak
